# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-06-16 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_english', models.CharField(max_length=120)),
                ('name_hindi', models.CharField(max_length=120)),
                ('date', models.DateField(auto_now_add=True)),
                ('venue_engilsh', models.CharField(max_length=120)),
                ('venue_hindi', models.CharField(max_length=120)),
                ('description_english', models.TextField()),
                ('description_hindi', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='media/campaign_images')),
            ],
        ),
    ]
