# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-06-17 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigndata',
            name='description_english',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaigndata',
            name='description_hindi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaigndata',
            name='name_english',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='campaigndata',
            name='name_hindi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='campaigndata',
            name='venue_engilsh',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='campaigndata',
            name='venue_hindi',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
