# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-23 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_auto_20170617_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigndata',
            name='date',
            field=models.DateField(),
        ),
    ]
