# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-22 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_us', '0004_auto_20170621_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinusdata',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
