# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-06-17 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagedata',
            name='campaign_id',
        ),
        migrations.RemoveField(
            model_name='videodata',
            name='campaign_id',
        ),
        migrations.AlterField(
            model_name='videodata',
            name='video',
            field=models.CharField(max_length=100),
        ),
    ]
