# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-06-17 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
        ('gallery', '0002_auto_20170617_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagedata',
            name='campaign_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='campaign.CampaignData'),
        ),
        migrations.AddField(
            model_name='videodata',
            name='campaign_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='campaign.CampaignData'),
        ),
    ]
