# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-06-17 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20170617_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videodata',
            name='video',
            field=models.FileField(upload_to='media/gallery/video/'),
        ),
    ]
