# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-06-17 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20170617_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedata',
            name='caption_english',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='imagedata',
            name='caption_hindi',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='videodata',
            name='caption_english',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='videodata',
            name='caption_hindi',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
