# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-22 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20170617_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedata',
            name='campaign_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaign.CampaignData'),
        ),
        migrations.AlterField(
            model_name='videodata',
            name='campaign_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaign.CampaignData'),
        ),
    ]
