# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-23 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0002_aboutusdata_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutTheTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile', models.IntegerField()),
                ('image', models.ImageField(upload_to='about_us/')),
            ],
        ),
        migrations.AddField(
            model_name='aboutusdata',
            name='achievements_en',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='aboutusdata',
            name='achievements_hindi',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='aboutusdata',
            name='introduction_en',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='aboutusdata',
            name='introduction_hindi',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='aboutusdata',
            name='vision_english',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='aboutusdata',
            name='vision_hindi',
            field=models.TextField(default=''),
        ),
    ]
