# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-23 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0003_auto_20170623_1252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutusdata',
            old_name='achievements_en',
            new_name='achievements_english',
        ),
        migrations.RenameField(
            model_name='aboutusdata',
            old_name='introduction_en',
            new_name='introduction_english',
        ),
        migrations.RemoveField(
            model_name='abouttheteam',
            name='name',
        ),
        migrations.RemoveField(
            model_name='aboutusdata',
            name='description_english',
        ),
        migrations.RemoveField(
            model_name='aboutusdata',
            name='description_hindi',
        ),
        migrations.RemoveField(
            model_name='aboutusdata',
            name='title_english',
        ),
        migrations.RemoveField(
            model_name='aboutusdata',
            name='title_hindi',
        ),
        migrations.AddField(
            model_name='abouttheteam',
            name='name_english',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='abouttheteam',
            name='name_hindi',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
