# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-21 11:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('feedback', '0003_feedbackdata_visibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackdata',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='feedbackdata',
            name='name',
        ),
        migrations.RemoveField(
            model_name='feedbackdata',
            name='ward',
        ),
        migrations.AddField(
            model_name='feedbackdata',
            name='user_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.UserData'),
        ),
    ]
