# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-23 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_userdata_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='image',
            field=models.ImageField(upload_to='profile/'),
        ),
    ]
