# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-06-17 11:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlikedata',
            name='shared',
        ),
    ]
