# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-06-17 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_remove_userlikedata_shared'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlikedata',
            name='shared',
            field=models.BooleanField(default=False),
        ),
    ]
