# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-20 07:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('story', '0004_auto_20170620_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlikedata',
            name='user_mobile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.UserData'),
        ),
        migrations.AlterField(
            model_name='userlikedata',
            name='user_id',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
