# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-20 08:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('story', '0005_auto_20170620_0753'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserShareData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0, editable=False)),
                ('shared', models.BooleanField(default=False)),
                ('story_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='story.StoryData')),
                ('user_mobile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.UserData')),
            ],
        ),
        migrations.RemoveField(
            model_name='userlikedata',
            name='shared',
        ),
    ]
