# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-20 09:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0006_auto_20170620_0833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storydata',
            old_name='description_english',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='storydata',
            old_name='description_hindi',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='storydata',
            name='title_english',
        ),
        migrations.RemoveField(
            model_name='storydata',
            name='title_hindi',
        ),
    ]
