# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-06-20 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0008_storydata_approve'),
    ]

    operations = [
        migrations.AddField(
            model_name='storydata',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
