# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-21 08:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0010_remove_storydata_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storydata',
            old_name='user_mobile',
            new_name='user_data',
        ),
        migrations.RemoveField(
            model_name='storydata',
            name='user_id',
        ),
    ]
