# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-21 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0011_auto_20170621_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storydata',
            name='image',
            field=models.ImageField(upload_to='media/media/story/images/'),
        ),
    ]
