# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-21 08:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0012_auto_20170621_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlikedata',
            name='user_mobile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.UserData'),
        ),
    ]
