# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-21 09:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0015_auto_20170621_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlikedata',
            name='story_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='story.StoryData'),
        ),
    ]
