# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-17 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('mobile', models.CharField(blank=True, max_length=120, null=True)),
                ('address_hindi', models.CharField(blank=True, max_length=200, null=True)),
                ('address_english', models.CharField(blank=True, max_length=200, null=True)),
                ('name_hindi', models.CharField(blank=True, max_length=120, null=True)),
                ('name_english', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
    ]
