# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-17 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splash_screen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagedata',
            name='value',
        ),
        migrations.AddField(
            model_name='imagedata',
            name='image',
            field=models.ImageField(default='/media/images/default.png', upload_to='images/'),
        ),
    ]
