# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-06-19 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splash_screen', '0002_auto_20170617_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcmdata',
            name='fcm',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
